### ISSUE TITLE
Cannot see diff lines

### ISSUE THREAD

**Issue by gabmontes** [miketheman/language-diff#10]
There is some bad interaction with the [GitHub's official light syntax theme](https://github.com/primer/github-atom-light-syntax/), making diff output unreadable. Using Atom as git commit editor. Changing themes to Atom default ones, all works OK.

![image](https://cloud.githubusercontent.com/assets/2621975/22041173/8351acf2-dce4-11e6-9eb2-7edc11f2d9db.png)

Opened another issue at the theme's tracking repo: https://github.com/primer/github-syntax-theme-generator/issues/30.

Please advise. Thanks!

Atom@1.3.0
github-atom-light-syntax@0.3.2
language-diff@0.7.0
language-git@0.15.0

**Comment by miketheman** [comment]
@gabmontes Thanks for reporting. I've added details on the other issue here: https://github.com/primer/github-syntax-theme-generator/issues/30#issuecomment-274989398

Closing, as it's the theme that needs a change here for Atom 1.13.

If after the theme package is updated and it still has issues, please reopen this case.

**Comment by gabmontes** [comment]
Thanks @miketheman!
