### ISSUE TITLE
Doesn't higlight '@@' markers

### ISSUE THREAD

**Issue by Techcable** [miketheman/language-diff#3]
![Screenshot](https://i.gyazo.com/f2545d229a1dd453d9abcd4d2e1f96a7.png)
Shouldn't "@@ -42,7 +42,7 @@" be highlighted?

**Comment by Techcable** [comment]
I see why they call it `the hackable editor`

```
atom-text-editor::shadow {
    .diff {
        &.range {
            color: orange
        }

        &.coordinates {
            color: orange
        }
    }
}
```

**Comment by deckar01** [comment]
@miketheman What do you think about adding some default color to ranges and headers? It's a little tough to read when the code is the same color as the diff headers.

**Comment by deckar01** [comment]
Here is a good example of using the existing added/removed colors for the header and dimming the coordinates:

![image](https://cloud.githubusercontent.com/assets/3108007/19356176/8b3e310e-9132-11e6-880b-4588c50c47f9.png)

http://www.colordiff.org/screenshots.html

**Comment by miketheman** [comment]
@deckar01 That does indeed seem to be a good feature we should have.

Care to take a crack at it? We've got a test suite that should add the detection of these scopes as well.
