### ISSUE TITLE
Feature Request: Better support for recursive diffs

### ISSUE THREAD

**Issue by peterstory** [miketheman/language-diff#5]
If you do a recursive diff to compare two directories, the output includes lines like:

```
Only in DIR_NAME: FILENAME
```

It would be great if the syntax could be modified to emphasize these lines in some way. Without emphasis, it's easy to overlook them, because the colored lines stand out much more. Perhaps bolding them would work well?

**Comment by miketheman** [comment]
Can you provide such an example in more complete form, so there's something to test it against?

**Comment by peterstory** [comment]
[old and new versions.zip](https://github.com/miketheman/language-diff/files/503233/old.and.new.versions.zip)
Sure thing! 

Here is the output of running `diff -ru old_version new_version`:

```
diff -ru old_version/file_a.txt new_version/file_a.txt
--- old_version/file_a.txt  2016-09-30 10:55:30.000000000 -0400
+++ new_version/file_a.txt  2016-09-30 10:56:13.000000000 -0400
@@ -1,2 +1,4 @@
 This is a very important file.
 It contains a lot of useful data.
+
+No, this file doesn't contain anything useful at all! 
Only in new_version: file_b.txt
```

**Comment by miketheman** [comment]
@peterstory Thanks!

I've got a simple fix ready, where it uses the theme's colors adds `bold` to it and uses the `function` syntax highlighter. Here's what it looks like:

# Solarized Dark

<img width="563" alt="screenshot 2016-10-01 07 15 35" src="https://cloud.githubusercontent.com/assets/529516/19013720/f57cf180-87a6-11e6-93d4-3d94e561ec17.png">

# One Light

<img width="545" alt="screenshot 2016-10-01 07 15 49" src="https://cloud.githubusercontent.com/assets/529516/19013722/f582a83c-87a6-11e6-92cc-05fe45733344.png">

# Atom Light

<img width="539" alt="screenshot 2016-10-01 07 15 59" src="https://cloud.githubusercontent.com/assets/529516/19013721/f5806f7c-87a6-11e6-9b00-66b8e2b9c033.png">

Let me know if you have any other thoughts before I release this in a few days.

**Comment by peterstory** [comment]
That looks really great! Thanks for making that improvement!

**Comment by miketheman** [comment]
Released. Enjoy!
