### ISSUE TITLE
Deprecated selector in `language-diff/styles/diff.less`

### ISSUE THREAD

**Issue by mikestreety** [miketheman/language-diff#7]
In `language-diff/styles/diff.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .diff.inserted` => `atom-text-editor.editor .syntax--diff.syntax--inserted`

* `atom-text-editor::shadow .diff.changed` => `atom-text-editor.editor .syntax--diff.syntax--changed`

* `atom-text-editor::shadow .diff.deleted` => `atom-text-editor.editor .syntax--diff.syntax--deleted`

* `atom-text-editor::shadow .diff.only-in` => `atom-text-editor.editor .syntax--diff.syntax--only-in`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by miketheman** [comment]
Hi @mikestreety !

Thanks for reporting - do you have any idea how and when this changed? If I update the diff package to support the new approach, and someone's not on the latest release, will they be broken?

**Comment by mikestreety** [comment]
Hello! 

Sorry for the impersonal message - that was the one automated from Atom 😄 

I'm running the beta, `1.13.0-beta2` which is where this message appeared.

This looks like it has some handy info - appears you need to specify in your `package.json` the version it supports.

http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html

Thanks!

**Comment by miketheman** [comment]
@mikestreety I pushed a branch that addresses these changes here:
https://github.com/miketheman/language-diff/tree/style-deprecation-1.13 with cee2a9f80e7522ea3605a40e64a10c4671edb23d

Since Atom 1.13 is still beta, I won't release it just yet. Can you try testing it locally? You should be able to drop the changed file into the same location.

**Comment by mikestreety** [comment]
I've just copied and pasted the code and works fine.

Thanks!

**Comment by vforge** [comment]
Atom 1.13.0 was released.

**Comment by miketheman** [comment]
language-diff 0.7.0 was released with this fix. https://github.com/miketheman/language-diff/releases/tag/v0.7.0
